Host = "127.0.0.1"
User = "mqtt_user"
Pass = "mqtt_pass"
DeviceName = "WIMATRIX"
TwitchOAuthClient = ""
TwitchOAuthSecret = ""
RewardTitle = "HUEPanel"
LightRewardTitle = "Apertar botão da luz"
CodeReviewRewardTitle = "CODEREVIEW"
TwitchCallbackBase = "http://localhost:7002"
TwitchCallSecret = "johnhuebr"
DiscordBotOutputUrl = ""
DiscordLogOutputUrl = ""
LogIgnoreList = "nightbot,streamelements"